# -*- coding: utf-8 -*-
"""Hijri_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mis2RlX1I_fnCxuj3DEFDd7O5FzWDpij
"""

import subprocess
import sys

try:
    import convertdate
except ImportError:
    print("Installing missing dependency: convertdate...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "convertdate"])
    import convertdate

from datetime import date
from convertdate import islamic

# A helper dict to map Hijri month numbers to their names
HIJRI_MONTH_NAMES = {
    1:  "Muharram",
    2:  "Safar",
    3:  "Rabi' al-Awwal",
    4:  "Rabi' al-Thani",
    5:  "Jumada al-Awwal",
    6:  "Jumada al-Thani",
    7:  "Rajab",
    8:  "Sha'ban",
    9:  "Ramadan",
    10: "Shawwal",
    11: "Dhu al-Qa'dah",
    12: "Dhu al-Hijjah"
}

def is_hijri_leap(year):
    """
    Returns True if the given Hijri year is a leap year.
    Standard rule: if ((11 * year + 14) % 30) is less than 11.
    """
    return ((11 * year + 14) % 30) < 11

def get_hijri_month_length(year, month):
    """
    Returns the number of days in the given Hijri month for a particular year,
    based on the tabular Islamic calendar.
    """
    if month % 2 == 1:
        # Odd months are 30 days
        return 30
    else:
        # Even months are 29 days, except month 12 in a leap year.
        if month == 12 and is_hijri_leap(year):
            return 30
        return 29

def calculate_hijri_age(birth_hijri, current_hijri):
    """
    Given two Hijri dates as (year, month, day), compute the difference
    in years, months, and days.
    """
    by, bm, bd = birth_hijri
    cy, cm, cd = current_hijri

    years_diff = cy - by
    months_diff = cm - bm
    days_diff = cd - bd

    if days_diff < 0:
        months_diff -= 1

        prev_month = cm - 1
        prev_year = cy
        if prev_month == 0:
            prev_month = 12
            prev_year -= 1
        days_diff += get_hijri_month_length(prev_year, prev_month)


    if months_diff < 0:
        months_diff += 12
        years_diff -= 1

    return years_diff, months_diff, days_diff

def main():
    # 1) Prompt the user for Gregorian birthday
    gregorian_birthday_str = input("Enter your birthday (YYYY-MM-DD): ")
    gy, gm, gd = map(int, gregorian_birthday_str.split('-'))

    # 2) Convert the Gregorian birthday to the Hijri date
    hyear, hmonth, hday = islamic.from_gregorian(gy, gm, gd)
    birth_hijri = (hyear, hmonth, hday)

    # Lookup the Hijri month name
    hijri_month_name = HIJRI_MONTH_NAMES.get(hmonth, "Unknown month")

    # 3) Print your Hijri birthday
    print(f"\nYour Hijri birthday is approximately {hday}-{hmonth}-{hyear}")
    print(f"Which is {hday} {hijri_month_name} {hyear} in the Islamic calendar.\n")

    # 4) Convert today's Gregorian date to Hijri date
    today = date.today()
    current_hijri = islamic.from_gregorian(today.year, today.month, today.day)

    # 5) Calculate your Hijri age in years, months, and days
    years, months, days = calculate_hijri_age(birth_hijri, current_hijri)
    print(f"Your Hijri age as of today is {years} years, {months} months, and {days} days.")

if __name__ == "__main__":
    main()